config/routes.rb
Plebe::Application.routes.draw do
  

  resources :users   # get "users/new"
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => 'pages#home'
  
  match '/help',        :to => 'pages#help'
  match '/profile',     :to => 'pages#profile'
  match '/about',       :to => 'pages#about'
  match '/support',     :to => 'pages#support'
  match '/developers',  :to => 'pages#developers'
  match '/signup',      :to => 'users#new'
  match '/comingsoon',  :to => 'pages#comingsoon'
  match '/signin',      :to => 'sessions#new'
  match '/signout',     :to => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor   :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,  :presence => true,
                    :length   => { :maximum => 50 }
  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }
  
  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  class << self
    def User.authenticate(email, submitted_password)
      user = find_by_email(email)
      (user && user.has_password?(submitted_password)) ? user :nil
    end
    
    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
    
  end    
  
  private
  
  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(self.password)
  end
  
  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end
  
  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end
  
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end



end


# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    @comingsoon = "1"
  end

  def help
    @title = "Help"
  end

  def profile
    @title = "Profile"
  end

  def about
    @title = "About"
  end

  def support
    @title = "Support"
  end

  def developers
    @title = "Developers"
  end
  
  def comingsoon
    render :layout => false
    @title = "Home"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end
  
  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_to user_path(user)
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def new
    @user = User.new
    @title = "Sign up"
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Plebe"
      redirect_to  user_path(@user)
    else
      @title = "Sign up"
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Return a title on a per page basis
  def title
    base_title = "Plebe"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  private
  
    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end
    
    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
  
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user, options = { :size => 150 })
    gravatar_image_tag(user.email.downcase, :alt      => user.name,
                                            :class    => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Developers", developers_path %></li>
			<li><%= link_to "Support", support_path %></li>
			<li><%= link_to "Help", help_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<% logo = image_tag("logo.png", :alt => "Plebian App", :class => "round") %>
	<%= link_to logo, root_path %>
	<nav class="round">
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<% if signed_in? %>
				<li><%= link_to "Profile", user_path(current_user) %></li>
			<% end %>
			<li><%= link_to "Help", help_path %></li>
			<% if signed_in? %>
				<li><%= link_to "Sign out", signout_path %></li>
			<% else %>
				<li><%= link_to "Sign in", signin_path %></li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen'%>
  <%= stylesheet_link_tag "blueprint/screen", :media => "print" %>
  <!--[if lt IE 8]>
  	<%= stylesheet_link_tag 'blueprint/ie' %>
  	<![endif]-->
  	<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets'%>
</head>
<body>
	<div class="container">
		<%= render 'layouts/header'%>
		<section class="round">
			<% flash.each do |key, value| %>
				<div class="flash <%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
		</section>
		<%= render 'layouts/footer'%>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>nice try, still under wraps!</p>

app/views/pages/comingsoon.html.erb
<head>
	<title><%= "Home" %></title>
</head>
<body>
	<%= image_tag("comingsoon.png", :alt => "Spin Baby Spin", :class => "splashimage" )%>
</body>

app/views/pages/developers.html.erb
<h1>Developers</h1>
<p>Developers tools and APIs coming soon</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<div class="body"><p>1 I'll take help wherever I can find it | this may be of help to you: assistance, aid, a helping hand, support, succor, advice, guidance; benefit, use, advantage, service, comfort; informal a shot in the arm.</p>
<p>2 he sought help for his eczema: relief, alleviation, improvement, assuagement, healing; a remedy, a cure, a restorative.
</p>
<p>3 they treated the help badly: domestic worker, domestic servant, cleaner, cleaning lady, housekeeper, maid, hired help, helper.
</p>
</div>

app/views/pages/home.html.erb
<p>
 CODENAME: Plebe
 plebe |plēb| noun
a newly entered cadet or freshman, esp. at a military academy.
The plebs was the general body of free landowning Roman citizens (as distinguished from slaves) in Ancient Rome. They were distinct from the higher order of the patricians. A member of the plebs was known as a plebeian ( /plɪˈbiːən/; Latin: plebeius). This term is used today to refer to one who is or appears to be of the middle or lower order; however, in Rome plebeians could become quite wealthy and influential.
</p>

<%= image_tag("spinning_record.gif", :alt => "Spin Baby Spin", :class => "splashimage" )%>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/pages/profile.html.erb
<h1>Profile</h1>
<p>Great profile, you should work on your head shot</p>

app/views/pages/signout.html.erb
<h1>Pages#signout</h1>
<p>Find me in app/views/pages/signout.html.erb</p>

app/views/pages/support.html.erb
<h1>Support</h1>
<p>Once we get going, support will surely follow</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<h2>
			<%= pluralize(@user.errors.count, "error") %>
			prohibited this user from being saved: 
		</h2>
		<p>There were problems with the following fields:</p>
		<ul>
		<% @user.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>	
		</ul>
	</div> 
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="action">
		<%= f.submit "Sign up" %>
	</div>

<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile Information">
	<tr>
		<td>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</td>
		<td class="sidebar round">
			<strong>Name</strong> <%= @user.name %><br />
			<strong>URL</strong> <%= link_to user_path(@user), @user %>
		</td>
	</tr>
</table>